# Fichier de configuration Traefik

# Configurations générales
global:
  checkNewVersion: true
  sendAnonymousUsage: true

# Configuration des entrées
entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

# Configuration des routages
http:
  routers:
    my-router:
      rule: "Host(`example.com`)"
      service: my-service
      entryPoints:
        - web

  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://backend-service"
