http:
  routers:
    wp:
      rule: "Host(`wp.local`)"
      service: "wp-service"
      entryPoints:
        - "http"
  services:
    wp-service:
      loadBalancer:
        healthCheck:
          path: "/health.php"
          interval: "10s"
        servers:
          - url: "http://wp-1:80"
          - url: "http://wp-2:80"
