[entryPoints]
  [entryPoints.http]
    address = ":80"

[api]
  dashboard = true
  insecure = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

  [providers.file]
    filename = "/etc/traefik/dynamic.yml"
    watch = true
